version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - app_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  jenkins_home:
  certs:
