version: '3'

services:
  # Jenkins for CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    container_name: ${JENKINS_CONTAINER_NAME:-jenkins}
    restart: unless-stopped
    user: root
    ports:
      - "${JENKINS_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - ./app:/var/jenkins_home/app

# Persistent volumes
volumes:
  jenkins_home:
