services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

volumes:
  jenkins_home:
