pipeline {
    agent any

    environment {
        BACKEND_REPO_URL = "git@github.com:DAW-Panaurum/paraurum-backend.git"
        FRONTEND_REPO_URL = "git@github.com:DAW-Panaurum/paraurum-frontend.git"
    }

    stages {
        stage('Clone Repositories') {
            steps {
                parallel (
                    Backend: {
                        dir('backend') {
                            git branch: 'main', url: "${BACKEND_REPO_URL}"
                        }
                    },
                    Frontend: {
                        dir('frontend') {
                            git branch: 'main', url: "${FRONTEND_REPO_URL}"
                        }
                    }
                )
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh '''
                        cp .env.example .env
                        composer install
                        php artisan key:generate
                        php artisan migrate --force
                    '''
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }

        stage('Deploy with Docker') {
            steps {
                sh '''
                    docker-compose down
                    docker-compose up -d --build
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
